name: Bug Report
description: File a bug report to help us improve
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees:
  - devops-team

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 2.1.x
        - 2.0.x
        - 1.9.x (not supported)
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Which environment is affected?
      options:
        - Production
        - Staging
        - Development
        - Local
    validations:
      required: true
